### PR TITLE
 UI fixes based around error handling and loading data into the app

### LINKED ISSUE #170: Harmonization and Calculate tab will cause fatal error if you click Harmonize Data with Synonym Table twice
**Describe the bug**

Harmonization and Calculate tab will cause fatal error if you click Harmonize Data with Synonym Table twice. 

**To Reproduce**

1. Open R Shiny app at https://rconnect-public.epa.gov/TADAShiny/
2. Remove Dates, add FORTPECK to organization & run query
3. Run flags, move to Harmonization and Calculate tab, and click Harmonize Data with Synonym Table twice

### LINKED ISSUE #196: Re-running 1. Load > Query Now results in instable session state
**Describe the bug**

If a user Queries and Flags and Censors data, and then returns to the 1/ Load tab and changes anything and re-runs Query then the UI is not reset to original state.  Tabs and Buttons are active that need to be inactive.

**To Reproduce**

1\. Query data using ORG_ID 21GUAM, no dates, Characteristic Enterococcus. Click Run Query

2\. Click on '3. Flag' and then hit the Flag button

3\. Click on '5. Censored Data' and turn the options to Non-Detect Handling Method No Change
and Over-Detect Handling Method to Multiple Limit by X and set x to 0.25

4\. Click on 'Apply Methods to Dataset' button

5\. Return to tab '1. Load' and add a second ORG_ID 21GUBCH

6\. Click Run Query.

7\. Click the '5. Censored Data'  tab

8\. The web application hits a fatal error
Error: (converted from warning) Error in : (converted from warning) Error in dplyr::group_by: Must group by variables found in `.data`.
✖ Column `TADA.CensoredData.Flag` is not found.

8\. scroll down and see that the 'Apply Methods to Dataset' button is still disabled, and the 'Undo Method Application' is active.

**Expected behavior**

The widgets on tab 1. Load should all be disabled once they have been run one time.  A new button should appear once a query has been run, or data loaded, and it should cause a complete Reload of the TADA Shiny app - setting state back to the initial state.

**Reminders for TADA contributors addressing this issue**

If users can load data during a session, all the session needs to be reset before the load occurs.  It might be possible to reset each object but it would be a developer burden - and I don't see that there is any benefit.

### LINKED ISSUE #222: 'Upload Successful' message should not be displayed when error message is displayed
**Describe the bug**

When importing data using Option C, the upload successful message should not be displayed if there is an error or warning message displayed. For example data to use when testing, see: https://github.com/USEPA/TADAShiny/issues/177

### LINKED ISSUE #223: cannot download example dataset again (issue with parameterization)
**Describe the bug**

After uploading an example dataset that was partially run through the app, and includes the 'parameterization' tab, I was not able to download the file again. The issue appears to be with how the app is reading and updating the 'Parameterization' tab in the uploaded file.

Specifically, there seems to be an error within utils_track_progress.R around line 174. I think we need to update the original source from example data to upload to handle this.

tadat$original_source == "Example" and should be updated to tadat$original_source == "Upload".... not sure where to implement but I think the issue is with our writeNarrativeDataFrame function.

**To Reproduce**

1. Go to 'Load'

2. Click on 'Upload data'

3. Load a dataset (exported from TADA as 'final)

This is the file that was generated and cannot be downloaded again. 
[test_tada_output_ts241104085033.xlsx](https://github.com/user-attachments/files/21006099/test_tada_output_ts241104085033.xlsx)

4. Try to download the file. 

See error: 

``` r
<simpleError in if (tadat$original_source == "Example") {    df[nrow(df) + 1, ] <- c("Example data file", tadat$example_data)} else if (tadat$original_source == "Query") {    query_params <- data.frame(param = c("State Code", "County Code",         "HUC Code", "Site ID", "Site Type", "Characteristic Name",         "Characteristic Type", "Sample Media", "Project Name",         "Organization Name", "Start Date", "End Date"), value = c(tadat$statecode,         tadat$countycode, tadat$huc, tadat$siteid, tadat$siteType,         tadat$characteristicName, tadat$characteristicType, tadat$sampleMedia,         tadat$project, tadat$organization, tadat$startDate, tadat$endDate))    for (i in seq_len(nrow(query_params))) {        if (!is.null(query_params[i, "value"])) {            df[nrow(df) + 1, ] <- query_params[i, ]        }    }}: argument is of length zero>
```

5. Try this again, but remove the parameterization tab in the example data excel file first. This same example data file works after removing 'Parameterization' tab from data upload file: 

[test2_tada_output_ts241104085033.xlsx](https://github.com/user-attachments/files/21006102/test2_tada_output_ts241104085033.xlsx)

**Expected behavior**

The parameterization tab should update and the file should be able to be downloaded again.

**Additional context**

See original issue here: https://github.com/USEPA/TADAShiny/issues/169

**Reminders for TADA contributors addressing this issue**

Bug fixes should include the following work:

-   [ ] Create or edit the code.

-   [ ] Document all code using line/inline and/or multi-line/block comments
    to describe what is does.

-   [ ] Create or edit tests in tests/testthat folder to help prevent and/or 
    troubleshoot potential future issues.

-   [ ] If your code edits impact other functionality in the shiny 
    app, ensure those are updated as well.

-   [ ] Run styler::style_pkg(), devtools::document(), and devtools::check() 
    and address any new notes or issues before creating a pull request.

### PR DESCRIPTION
**Pull request by JamesBisese**
First set of updates.  These are to address 5 tickets assigned to me.  There is some code reformatting just to make some large text blocks readable in RStudio.  The biggest UI change is that once a user has loaded data in the 'Load' tab all the buttons on that tab are disabled and messages added into the UI to tell the user that they need to reload TADAShiny app if they want to load new data.

### CODE REVIEW

File: R/mod_query_data.R [hunk 1]
```diff
@@ -1,3 +1,4 @@
+library(shinyjs)
```
Comment (cristinamullin) [inline R/mod_query_data.R:1]: library(shinyjs) should not be included here. I will remove it.

Libraries are loaded automatically if they are included as imports in the description file found at the top level of the package. When developing, you can use devtools to load all libraries. See example code:

```r
> library(devtools)
Loading required package: usethis
Warning message:
package ‘devtools’ was built under R version 4.4.3 
> load_all()
ℹ Loading TADAShiny
Error in `load_all()`:
! Failed to load R/mod_query_data.R
Caused by error:
! (converted from warning) package ‘shinyjs’ was built under R version 4.4.3
Run `rlang::last_trace()` to see where the error occurred.
> document()
ℹ Updating TADAShiny documentation
ℹ Loading TADAShiny
```

File: R/mod_harmonize_np.R [hunk 2]
```diff
@@ -179,10 +223,35 @@ mod_harmonize_np_server <- function(id, tadat) {
...
+      # in case they want to undo and try another method instead
+      output$undo_harm_apply <- shiny::renderUI({
+        # shiny::req(censdat$exdat) # not sure what this does
+        shiny::actionButton(ns("undo_harm_apply"), 
+                            "Undo Harmonize Data with Synonym Table",
+                            style = "color: #fff; background-color: #337ab7; border-color: #2e6da4; margin-left: 10px;")
+        # shinyjs::enable("undo_harm_apply")
+      })
+
+      # executes the undo if 'Undo Harmonize Data with Synonym Table' is pressed.
```
Comment (cristinamullin) [inline R/mod_harmonize_np.R:244]: I think this needs to be a separate shiny::observeEvent. I am working on an update in the Aug-Deploy branch

**Review by cristinamullin — APPROVED** [review]
Approved with some minor changes I made on a separate branch. See: https://github.com/USEPA/TADAShiny/pull/246
